server:
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3307/homebanking?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      sqs:
        endpoint: http://localhost:4566

# Personalized properties
queue:
  name: transfer-queue

dolar:
  api:
    url: https://dolarapi.com