name: HomeBankingServices

services:
  postgres-db:
    image: postgres:17
    container_name: postgres-homebanking
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homebanking
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: ["postgres"]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d homebanking" ]
      interval: 10s
      timeout: 5s
      retries: 5

  localstack:
    image: localstack/localstack:4.4.0
    container_name: localstack-homebanking
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack-data:/var/lib/localstack

volumes:
  postgres-data:
  localstack-data: